title: My Tech Blog
description: A blog about tech
baseurl: "/my-tech-blog"   # repo name
url: "https://jayeshsharma2605.github.io"
theme: minima

# Optional: clean permalink for posts
permalink: /:categories/:title/
