title: My Tech Blog
description: A blog about tech and system design
baseurl: "" 
url: "https://yourusername.github.io"
theme: minima

collections:
  system_design:
    output: true
    permalink: /system_design/:title/
